# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.api.maintenance_api import MaintenanceApi  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestMaintenanceApi(unittest.TestCase):
    """MaintenanceApi unit test stubs"""

    def setUp(self):
        self.api = opsgenie_swagger.api.maintenance_api.MaintenanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_maintenance(self):
        """Test case for cancel_maintenance

        Cancel Maintenance  # noqa: E501
        """
        pass

    def test_create_maintenance(self):
        """Test case for create_maintenance

        Create Maintenance  # noqa: E501
        """
        pass

    def test_delete_maintenance(self):
        """Test case for delete_maintenance

        Delete Maintenance  # noqa: E501
        """
        pass

    def test_get_maintenance(self):
        """Test case for get_maintenance

        Get Maintenance  # noqa: E501
        """
        pass

    def test_list_maintenance(self):
        """Test case for list_maintenance

        List Maintenance  # noqa: E501
        """
        pass

    def test_update_maintenance(self):
        """Test case for update_maintenance

        Update Maintenance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
