# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.models.recipient import Recipient  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestRecipient(unittest.TestCase):
    """Recipient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecipient(self):
        """Test Recipient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsgenie_swagger.models.recipient.Recipient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
