# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.api.forwarding_rule_api import ForwardingRuleApi  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestForwardingRuleApi(unittest.TestCase):
    """ForwardingRuleApi unit test stubs"""

    def setUp(self):
        self.api = opsgenie_swagger.api.forwarding_rule_api.ForwardingRuleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_forwarding_rule(self):
        """Test case for create_forwarding_rule

        Create Forwarding Rule  # noqa: E501
        """
        pass

    def test_delete_forwarding_rule(self):
        """Test case for delete_forwarding_rule

        Delete Forwarding Rule  # noqa: E501
        """
        pass

    def test_get_forwarding_rule(self):
        """Test case for get_forwarding_rule

        Get Forwarding Rule  # noqa: E501
        """
        pass

    def test_list_forwarding_rules(self):
        """Test case for list_forwarding_rules

        List Forwarding Rules  # noqa: E501
        """
        pass

    def test_update_forwarding_rule(self):
        """Test case for update_forwarding_rule

        Update Forwarding Rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
