# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.api.schedule_override_api import ScheduleOverrideApi  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestScheduleOverrideApi(unittest.TestCase):
    """ScheduleOverrideApi unit test stubs"""

    def setUp(self):
        self.api = opsgenie_swagger.api.schedule_override_api.ScheduleOverrideApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_schedule_override(self):
        """Test case for create_schedule_override

        Create Schedule Override  # noqa: E501
        """
        pass

    def test_delete_schedule_override(self):
        """Test case for delete_schedule_override

        Delete Schedule Override  # noqa: E501
        """
        pass

    def test_get_schedule_override(self):
        """Test case for get_schedule_override

        Get Schedule Override  # noqa: E501
        """
        pass

    def test_list_schedule_override(self):
        """Test case for list_schedule_override

        List Schedule Overrides  # noqa: E501
        """
        pass

    def test_update_schedule_override(self):
        """Test case for update_schedule_override

        Update Schedule Override  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
