# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.api.contact_api import ContactApi  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestContactApi(unittest.TestCase):
    """ContactApi unit test stubs"""

    def setUp(self):
        self.api = opsgenie_swagger.api.contact_api.ContactApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_contact(self):
        """Test case for create_contact

        Create Contact  # noqa: E501
        """
        pass

    def test_delete_contact(self):
        """Test case for delete_contact

        Delete Contact  # noqa: E501
        """
        pass

    def test_disable_contact(self):
        """Test case for disable_contact

        Disable Contact  # noqa: E501
        """
        pass

    def test_enable_contact(self):
        """Test case for enable_contact

        Enable Contact  # noqa: E501
        """
        pass

    def test_get_contact(self):
        """Test case for get_contact

        Get Contact  # noqa: E501
        """
        pass

    def test_list_contacts(self):
        """Test case for list_contacts

        List Contacts  # noqa: E501
        """
        pass

    def test_update_contact(self):
        """Test case for update_contact

        Update Contact (Partial)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
