# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.models.callback_condition import CallbackCondition  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestCallbackCondition(unittest.TestCase):
    """CallbackCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCallbackCondition(self):
        """Test CallbackCondition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsgenie_swagger.models.callback_condition.CallbackCondition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
