# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.api.account_api import AccountApi  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = opsgenie_swagger.api.account_api.AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_info(self):
        """Test case for get_info

        Get Account Info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
