# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.models.create_forwarding_rule_response import CreateForwardingRuleResponse  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestCreateForwardingRuleResponse(unittest.TestCase):
    """CreateForwardingRuleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateForwardingRuleResponse(self):
        """Test CreateForwardingRuleResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsgenie_swagger.models.create_forwarding_rule_response.CreateForwardingRuleResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
