# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.models.timeline_period import TimelinePeriod  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestTimelinePeriod(unittest.TestCase):
    """TimelinePeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimelinePeriod(self):
        """Test TimelinePeriod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsgenie_swagger.models.timeline_period.TimelinePeriod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
