# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.models.escalation_repeat import EscalationRepeat  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestEscalationRepeat(unittest.TestCase):
    """EscalationRepeat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEscalationRepeat(self):
        """Test EscalationRepeat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsgenie_swagger.models.escalation_repeat.EscalationRepeat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
