# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.api.schedule_api import ScheduleApi  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestScheduleApi(unittest.TestCase):
    """ScheduleApi unit test stubs"""

    def setUp(self):
        self.api = opsgenie_swagger.api.schedule_api.ScheduleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_schedule(self):
        """Test case for create_schedule

        Create Schedule  # noqa: E501
        """
        pass

    def test_delete_schedule(self):
        """Test case for delete_schedule

        Delete Schedule  # noqa: E501
        """
        pass

    def test_export_schedule(self):
        """Test case for export_schedule

        Export Schedule  # noqa: E501
        """
        pass

    def test_get_schedule(self):
        """Test case for get_schedule

        Get Schedule  # noqa: E501
        """
        pass

    def test_get_schedule_timeline(self):
        """Test case for get_schedule_timeline

        Get Schedule Timeline  # noqa: E501
        """
        pass

    def test_list_schedules(self):
        """Test case for list_schedules

        List Schedules  # noqa: E501
        """
        pass

    def test_update_schedule(self):
        """Test case for update_schedule

        Update Schedule (Partial)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
