# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.models.new_relic_v2_integration import NewRelicV2Integration  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestNewRelicV2Integration(unittest.TestCase):
    """NewRelicV2Integration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewRelicV2Integration(self):
        """Test NewRelicV2Integration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsgenie_swagger.models.new_relic_v2_integration.NewRelicV2Integration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
