# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opsgenie_swagger
from opsgenie_swagger.models.uptime_webhook_integration import UptimeWebhookIntegration  # noqa: E501
from opsgenie_swagger.rest import ApiException


class TestUptimeWebhookIntegration(unittest.TestCase):
    """UptimeWebhookIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUptimeWebhookIntegration(self):
        """Test UptimeWebhookIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opsgenie_swagger.models.uptime_webhook_integration.UptimeWebhookIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
