# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.account_plan import AccountPlan  # noqa: F401,E501


class AccountInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'user_count': 'int',
        'plan': 'AccountPlan'
    }

    attribute_map = {
        'name': 'name',
        'user_count': 'userCount',
        'plan': 'plan'
    }

    def __init__(self, name=None, user_count=None, plan=None):  # noqa: E501
        """AccountInfo - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._user_count = None
        self._plan = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if user_count is not None:
            self.user_count = user_count
        if plan is not None:
            self.plan = plan

    @property
    def name(self):
        """Gets the name of this AccountInfo.  # noqa: E501


        :return: The name of this AccountInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AccountInfo.


        :param name: The name of this AccountInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def user_count(self):
        """Gets the user_count of this AccountInfo.  # noqa: E501


        :return: The user_count of this AccountInfo.  # noqa: E501
        :rtype: int
        """
        return self._user_count

    @user_count.setter
    def user_count(self, user_count):
        """Sets the user_count of this AccountInfo.


        :param user_count: The user_count of this AccountInfo.  # noqa: E501
        :type: int
        """

        self._user_count = user_count

    @property
    def plan(self):
        """Gets the plan of this AccountInfo.  # noqa: E501


        :return: The plan of this AccountInfo.  # noqa: E501
        :rtype: AccountPlan
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this AccountInfo.


        :param plan: The plan of this AccountInfo.  # noqa: E501
        :type: AccountPlan
        """

        self._plan = plan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
