# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ChangeTeamRoutingRuleOrderPayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order': 'int'
    }

    attribute_map = {
        'order': 'order'
    }

    def __init__(self, order=None):  # noqa: E501
        """ChangeTeamRoutingRuleOrderPayload - a model defined in Swagger"""  # noqa: E501

        self._order = None
        self.discriminator = None

        if order is not None:
            self.order = order

    @property
    def order(self):
        """Gets the order of this ChangeTeamRoutingRuleOrderPayload.  # noqa: E501

        Order of team routing rule within the rules. order value is actually the index of the team routing rule.  # noqa: E501

        :return: The order of this ChangeTeamRoutingRuleOrderPayload.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this ChangeTeamRoutingRuleOrderPayload.

        Order of team routing rule within the rules. order value is actually the index of the team routing rule.  # noqa: E501

        :param order: The order of this ChangeTeamRoutingRuleOrderPayload.  # noqa: E501
        :type: int
        """

        self._order = order

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChangeTeamRoutingRuleOrderPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
