# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.user_meta import UserMeta  # noqa: F401,E501


class CreateForwardingRulePayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'from_user': 'UserMeta',
        'to_user': 'UserMeta',
        'start_date': 'datetime',
        'end_date': 'datetime',
        'alias': 'str'
    }

    attribute_map = {
        'from_user': 'fromUser',
        'to_user': 'toUser',
        'start_date': 'startDate',
        'end_date': 'endDate',
        'alias': 'alias'
    }

    def __init__(self, from_user=None, to_user=None, start_date=None, end_date=None, alias=None):  # noqa: E501
        """CreateForwardingRulePayload - a model defined in Swagger"""  # noqa: E501

        self._from_user = None
        self._to_user = None
        self._start_date = None
        self._end_date = None
        self._alias = None
        self.discriminator = None

        self.from_user = from_user
        self.to_user = to_user
        self.start_date = start_date
        self.end_date = end_date
        if alias is not None:
            self.alias = alias

    @property
    def from_user(self):
        """Gets the from_user of this CreateForwardingRulePayload.  # noqa: E501

        The user whose notifications will be forwarded.  # noqa: E501

        :return: The from_user of this CreateForwardingRulePayload.  # noqa: E501
        :rtype: UserMeta
        """
        return self._from_user

    @from_user.setter
    def from_user(self, from_user):
        """Sets the from_user of this CreateForwardingRulePayload.

        The user whose notifications will be forwarded.  # noqa: E501

        :param from_user: The from_user of this CreateForwardingRulePayload.  # noqa: E501
        :type: UserMeta
        """
        if from_user is None:
            raise ValueError("Invalid value for `from_user`, must not be `None`")  # noqa: E501

        self._from_user = from_user

    @property
    def to_user(self):
        """Gets the to_user of this CreateForwardingRulePayload.  # noqa: E501

        The user who will receive the forwarded notifications.  # noqa: E501

        :return: The to_user of this CreateForwardingRulePayload.  # noqa: E501
        :rtype: UserMeta
        """
        return self._to_user

    @to_user.setter
    def to_user(self, to_user):
        """Sets the to_user of this CreateForwardingRulePayload.

        The user who will receive the forwarded notifications.  # noqa: E501

        :param to_user: The to_user of this CreateForwardingRulePayload.  # noqa: E501
        :type: UserMeta
        """
        if to_user is None:
            raise ValueError("Invalid value for `to_user`, must not be `None`")  # noqa: E501

        self._to_user = to_user

    @property
    def start_date(self):
        """Gets the start_date of this CreateForwardingRulePayload.  # noqa: E501

        The date and time for forwarding will start  # noqa: E501

        :return: The start_date of this CreateForwardingRulePayload.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this CreateForwardingRulePayload.

        The date and time for forwarding will start  # noqa: E501

        :param start_date: The start_date of this CreateForwardingRulePayload.  # noqa: E501
        :type: datetime
        """
        if start_date is None:
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this CreateForwardingRulePayload.  # noqa: E501

        The date and time for forwarding will end  # noqa: E501

        :return: The end_date of this CreateForwardingRulePayload.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this CreateForwardingRulePayload.

        The date and time for forwarding will end  # noqa: E501

        :param end_date: The end_date of this CreateForwardingRulePayload.  # noqa: E501
        :type: datetime
        """
        if end_date is None:
            raise ValueError("Invalid value for `end_date`, must not be `None`")  # noqa: E501

        self._end_date = end_date

    @property
    def alias(self):
        """Gets the alias of this CreateForwardingRulePayload.  # noqa: E501

        A user defined identifier for the forwarding rule.  # noqa: E501

        :return: The alias of this CreateForwardingRulePayload.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this CreateForwardingRulePayload.

        A user defined identifier for the forwarding rule.  # noqa: E501

        :param alias: The alias of this CreateForwardingRulePayload.  # noqa: E501
        :type: str
        """

        self._alias = alias

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateForwardingRulePayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
