# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.alert_filter import AlertFilter  # noqa: F401,E501
from opsgenie_swagger.models.outgoing_callback import OutgoingCallback  # noqa: F401,E501


class FlowdockV2Callback(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'flowdock_flow_token': 'str'
    }

    attribute_map = {
        'flowdock_flow_token': 'flowdockFlowToken'
    }

    def __init__(self, flowdock_flow_token=None):  # noqa: E501
        """FlowdockV2Callback - a model defined in Swagger"""  # noqa: E501

        self._flowdock_flow_token = None
        self.discriminator = None

        if flowdock_flow_token is not None:
            self.flowdock_flow_token = flowdock_flow_token

    @property
    def flowdock_flow_token(self):
        """Gets the flowdock_flow_token of this FlowdockV2Callback.  # noqa: E501


        :return: The flowdock_flow_token of this FlowdockV2Callback.  # noqa: E501
        :rtype: str
        """
        return self._flowdock_flow_token

    @flowdock_flow_token.setter
    def flowdock_flow_token(self, flowdock_flow_token):
        """Sets the flowdock_flow_token of this FlowdockV2Callback.


        :param flowdock_flow_token: The flowdock_flow_token of this FlowdockV2Callback.  # noqa: E501
        :type: str
        """

        self._flowdock_flow_token = flowdock_flow_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FlowdockV2Callback):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
