# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.team_meta import TeamMeta  # noqa: F401,E501


class Integration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'id': 'str',
        'name': 'str',
        'enabled': 'bool',
        'owner_team': 'TeamMeta',
        'is_global': 'bool',
        'read_only': 'list[str]'
    }

    attribute_map = {
        'type': 'type',
        'id': 'id',
        'name': 'name',
        'enabled': 'enabled',
        'owner_team': 'ownerTeam',
        'is_global': 'isGlobal',
        'read_only': '_readOnly'
    }

    discriminator_value_class_map = {
        'AppDynamics': 'AppDynamicsIntegration',
        'Monitis': 'MonitisIntegration',
        'NewRelic': 'NewRelicIntegration',
        'CloudMonix': 'CloudMonixIntegration',
        'Scout': 'ScoutIntegration',
        'AmazonRds': 'AmazonRdsIntegration',
        'Detectify': 'DetectifyIntegration',
        'RedGateSqlMonitorEmail': 'RedGateSqlMonitorEmailIntegration',
        'DataloopIO': 'DataloopIOIntegration',
        'Site24x7': 'Site24x7Integration',
        'AmazonSns': 'AmazonSnsIntegration',
        'AlertLogic': 'AlertLogicIntegration',
        'RingCentralEmail': 'RingCentralEmailIntegration',
        'PagerDutyCompatibility': 'PagerDutyCompatibilityIntegration',
        'Honeybadger': 'HoneybadgerIntegration',
        'Freshservice': 'FreshserviceIntegration',
        'MongoDBCloud': 'MongoDBCloudIntegration',
        'Tideways': 'TidewaysIntegration',
        'AmazonCloudTrail': 'AmazonCloudTrailIntegration',
        'ObserviumV2': 'ObserviumV2Integration',
        'Kore': 'KoreIntegration',
        'AmazonSnsOutgoing': 'AmazonSnsOutgoingIntegration',
        'NeustarEmail': 'NeustarIntegration',
        'ServiceNowV2': 'ServiceNowV2Integration',
        'Catchpoint': 'CatchpointIntegration',
        'SolarwindsMSPNCentral': 'SolarwindsMSPNCentralIntegration',
        'Prometheus': 'PrometheusIntegration',
        'Boundary': 'BoundaryIntegration',
        'Librato': 'LibratoIntegration',
        'Campfire': 'CampfireIntegration',
        'SumoLogic': 'SumoLogicIntegration',
        'Papertrail': 'PapertrailIntegration',
        'Icinga2': 'Icinga2Integration',
        'Ruxit': 'DynatraceIntegration',
        'SolarWindsWebHelpDesk': 'SolarWindsWebHelpDeskIntegration',
        'Moxtra': 'MoxtraIntegration',
        'DNSCheck': 'DNSCheckIntegration',
        'Cherwell': 'CherwellIntegration',
        'DripStat': 'DripStatIntegration',
        'Panopta': 'PanoptaIntegration',
        'AlertSite': 'AlertSiteIntegration',
        'UptimeRobot': 'UptimeRobotIntegration',
        'Flowdock': 'FlowdockIntegration',
        'CloudWatch': 'CloudWatchIntegration',
        'Rigor': 'RigorIntegration',
        'AzureOMS': 'AzureOMSIntegration',
        'NodePing': 'NodePingIntegration',
        'Zendesk': 'ZendeskIntegration',
        'PingdomV2': 'PingdomV2Integration',
        'Twilio': 'TwilioCIIntegration',
        'FlowdockV2': 'FlowdockV2Integration',
        'Freshdesk': 'FreshdeskIntegration',
        'Riemann': 'RiemannIntegration',
        'AutoTaskEmail': 'AutoTaskEmailIntegration',
        'Azure': 'AzureIntegration',
        'Compose': 'ComposeIntegration',
        'Splunk': 'SplunkIntegration',
        'NewRelicV2': 'NewRelicV2Integration',
        'CheckMK': 'CheckMKIntegration',
        'Kayako': 'KayakoIntegration',
        'OpsDash': 'OpsDashIntegration',
        'Codeship': 'CodeshipIntegration',
        'LogzIO': 'LogzIOIntegration',
        'OEM': 'OEMIntegration',
        'API': 'ApiIntegration',
        'Logstash': 'LogstashIntegration',
        'Consul': 'ConsulIntegration',
        'Runscope': 'RunscopeIntegration',
        'SematextSpm': 'SematextSpmIntegration',
        'AmazonEc2AutoScaling': 'AmazonEc2AutoScalingIntegration',
        'Solarwinds': 'SolarwindsIntegration',
        'Logentries': 'LogentriesIntegration',
        'OP5': 'Op5Integration',
        'Marid': 'MaridIntegration',
        'Planio': 'PlanioIntegration',
        'Crashlytics': 'CrashlyticsIntegration',
        'Soasta': 'SoastaIntegration',
        'Circonus': 'CirconusIntegration',
        'HostedGraphite': 'HostedGraphiteIntegration',
        'ThousandEyes': 'ThousandEyesIntegration',
        'Airbrake': 'AirbrakeIntegration',
        'ESWatcher': 'XPackAlertingIntegration',
        'MSTeams': 'MSTeamsIntegration',
        'Desk': 'DeskIntegration',
        'StatusCake': 'StatusCakeIntegration',
        'Email': 'EmailIntegration',
        'CircleCi': 'CircleCiIntegration',
        'Zabbix': 'ZabbixIntegration',
        'TravisCI': 'TravisCIIntegration',
        'Icinga': 'IcingaIntegration',
        'Pingometer': 'PingometerIntegration',
        'SCOM': 'SCOMIntegration',
        'Atatus': 'AtatusIntegration',
        'CloudSploit': 'CloudSploitIntegration',
        'UptrendsEmail': 'UptrendsEmailIntegration',
        'JiraServiceDesk': 'JiraServiceDeskIntegration',
        'AutotaskAEMEmail': 'AutoTaskAEMEmailIntegration',
        'CopperEgg': 'CopperEggIntegration',
        'Datadog': 'DatadogIntegration',
        'StruxureWare': 'StruxureWareIntegration',
        'Heartbeat': 'HeartbeatIntegration',
        'Wavefront': 'WavefrontIntegration',
        'ServerDensity': 'ServerDensityIntegration',
        'Netuitive': 'NetuitiveIntegration',
        'ThreatStack': 'ThreatStackIntegration',
        'GhostInspector': 'GhostInspectorIntegration',
        'LabTechEmail': 'LabTechEmailIntegration',
        'AmazonRoute53HealthCheck': 'AmazonRoute53HealthCheckIntegration',
        'GoogleStackdriver': 'GoogleStackdriverIntegration',
        'OpsGenie': 'OpsgenieIntegration',
        'Zenoss': 'ZenossIntegration',
        'Jira': 'JiraIntegration',
        'Signalfx': 'SignalfxIntegration',
        'ConnectWise': 'ConnectWiseIntegration',
        'EvidentIO': 'EvidentIOIntegration',
        'VCenter': 'VCenterIntegration',
        'SignalSciences': 'SignalSciencesIntegration',
        'HipChatV2': 'HipchatV2Integration',
        'Graylog': 'GraylogIntegration',
        'Flock': 'FlockIntegration',
        'LogicMonitor': 'LogicMonitorIntegration',
        'Rackspace': 'RackspaceIntegration',
        'RingCentralGlip': 'RingCentralGlipIntegration',
        'Stackdriver': 'StackdriverIntegration',
        'SysdigCloud': 'SysdigCloudIntegration',
        'StatusPageIO': 'StatusPageIOIntegration',
        'NagiosV2': 'NagiosV2Integration',
        'Mattermost': 'MattermostIntegration',
        'NagiosXIV2': 'NagiosXIV2Integration',
        'StatusIO': 'StatusIOIntegration',
        'Errorception': 'ErrorceptionIntegration',
        'Scalyr': 'ScalyrIntegration',
        'UptimeWebhook': 'UptimeWebhookIntegration',
        'AmazonSes': 'AmazonSesIntegration',
        'AppSignal': 'AppSignalIntegration',
        'Sensu': 'SensuIntegration',
        'Webhook': 'WebhookIntegration',
        'Loggly': 'LogglyIntegration',
        'ServerGuard24': 'ServerGuard24Integration',
        'Rollbar': 'RollbarIntegration',
        'GrafanaV2': 'GrafanaV2Integration',
        'Prtg': 'PrtgIntegration'
    }

    def __init__(self, type=None, id=None, name=None, enabled=None, owner_team=None, is_global=None, read_only=None):  # noqa: E501
        """Integration - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._id = None
        self._name = None
        self._enabled = None
        self._owner_team = None
        self._is_global = None
        self._read_only = None
        self.discriminator = 'type'

        self.type = type
        if id is not None:
            self.id = id
        self.name = name
        if enabled is not None:
            self.enabled = enabled
        if owner_team is not None:
            self.owner_team = owner_team
        if is_global is not None:
            self.is_global = is_global
        if read_only is not None:
            self.read_only = read_only

    @property
    def type(self):
        """Gets the type of this Integration.  # noqa: E501

        Type of the integration. (For instance, \"API\" for API Integration)  # noqa: E501

        :return: The type of this Integration.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Integration.

        Type of the integration. (For instance, \"API\" for API Integration)  # noqa: E501

        :param type: The type of this Integration.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["Airbrake", "AlertLogic", "AlertSite", "AmazonCloudTrail", "AmazonEc2AutoScaling", "AmazonRds", "AmazonRoute53HealthCheck", "AmazonSes", "AmazonSns", "AmazonSnsOutgoing", "API", "AppDynamics", "AppSignal", "Atatus", "AutotaskAEMEmail", "AutoTaskEmail", "Azure", "AzureOMS", "Boundary", "Campfire", "Catchpoint", "CheckMK", "Cherwell", "CircleCi", "Circonus", "CloudMonix", "CloudSploit", "CloudWatch", "Codeship", "Compose", "ConnectWise", "Consul", "CopperEgg", "Crashlytics", "Datadog", "DataloopIO", "Desk", "Detectify", "DNSCheck", "DripStat", "Email", "Errorception", "ESWatcher", "EvidentIO", "Flock", "Flowdock", "FlowdockV2", "Freshdesk", "Freshservice", "GhostInspector", "GoogleStackdriver", "GrafanaV2", "Graylog", "Heartbeat", "HipChatV2", "Honeybadger", "HostedGraphite", "Icinga", "Icinga2", "Jira", "JiraServiceDesk", "Kayako", "Kore", "LabTechEmail", "Librato", "Logentries", "Loggly", "LogicMonitor", "Logstash", "LogzIO", "Marid", "Mattermost", "MongoDBCloud", "Monitis", "Moxtra", "MSTeams", "NagiosV2", "NagiosXIV2", "NeustarEmail", "Netuitive", "NewRelic", "NewRelicV2", "NodePing", "ObserviumV2", "OEM", "OP5", "OpsDash", "OpsGenie", "PagerDutyCompatibility", "Panopta", "Papertrail", "PingdomV2", "Pingometer", "Planio", "Prometheus", "Prtg", "Rackspace", "RedGateSqlMonitorEmail", "Riemann", "Rigor", "RingCentralEmail", "RingCentralGlip", "Rollbar", "Runscope", "Ruxit", "Scalyr", "SCOM", "Scout", "SematextSpm", "Sensu", "ServerDensity", "ServerGuard24", "ServiceNowV2", "Signalfx", "SignalSciences", "Site24x7", "Soasta", "Solarwinds", "SolarwindsMSPNCentral", "SolarWindsWebHelpDesk", "Splunk", "Stackdriver", "StatusCake", "StatusIO", "StatusPageIO", "StruxureWare", "SumoLogic", "SysdigCloud", "ThousandEyes", "ThreatStack", "Tideways", "TravisCI", "Twilio", "UptimeRobot", "UptimeWebhook", "UptrendsEmail", "VCenter", "Wavefront", "Webhook", "Zabbix", "Zendesk", "Zenoss"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def id(self):
        """Gets the id of this Integration.  # noqa: E501


        :return: The id of this Integration.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Integration.


        :param id: The id of this Integration.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Integration.  # noqa: E501

        Name of the integration. Name must be unique for each integration  # noqa: E501

        :return: The name of this Integration.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Integration.

        Name of the integration. Name must be unique for each integration  # noqa: E501

        :param name: The name of this Integration.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def enabled(self):
        """Gets the enabled of this Integration.  # noqa: E501

        This parameter is for specifying whether the integration will be enabled or not  # noqa: E501

        :return: The enabled of this Integration.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this Integration.

        This parameter is for specifying whether the integration will be enabled or not  # noqa: E501

        :param enabled: The enabled of this Integration.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def owner_team(self):
        """Gets the owner_team of this Integration.  # noqa: E501


        :return: The owner_team of this Integration.  # noqa: E501
        :rtype: TeamMeta
        """
        return self._owner_team

    @owner_team.setter
    def owner_team(self, owner_team):
        """Sets the owner_team of this Integration.


        :param owner_team: The owner_team of this Integration.  # noqa: E501
        :type: TeamMeta
        """

        self._owner_team = owner_team

    @property
    def is_global(self):
        """Gets the is_global of this Integration.  # noqa: E501


        :return: The is_global of this Integration.  # noqa: E501
        :rtype: bool
        """
        return self._is_global

    @is_global.setter
    def is_global(self, is_global):
        """Sets the is_global of this Integration.


        :param is_global: The is_global of this Integration.  # noqa: E501
        :type: bool
        """

        self._is_global = is_global

    @property
    def read_only(self):
        """Gets the read_only of this Integration.  # noqa: E501


        :return: The read_only of this Integration.  # noqa: E501
        :rtype: list[str]
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only):
        """Sets the read_only of this Integration.


        :param read_only: The read_only of this Integration.  # noqa: E501
        :type: list[str]
        """

        self._read_only = read_only

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Integration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
