# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.contact_meta import ContactMeta  # noqa: F401,E501
from opsgenie_swagger.models.duration import Duration  # noqa: F401,E501
from opsgenie_swagger.models.notification_rule_step_parent import NotificationRuleStepParent  # noqa: F401,E501


class NotificationRuleStep(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'parent': 'NotificationRuleStepParent',
        'id': 'str',
        'send_after': 'Duration',
        'contact': 'ContactMeta',
        'enabled': 'bool'
    }

    attribute_map = {
        'parent': '_parent',
        'id': 'id',
        'send_after': 'sendAfter',
        'contact': 'contact',
        'enabled': 'enabled'
    }

    def __init__(self, parent=None, id=None, send_after=None, contact=None, enabled=None):  # noqa: E501
        """NotificationRuleStep - a model defined in Swagger"""  # noqa: E501

        self._parent = None
        self._id = None
        self._send_after = None
        self._contact = None
        self._enabled = None
        self.discriminator = None

        if parent is not None:
            self.parent = parent
        if id is not None:
            self.id = id
        if send_after is not None:
            self.send_after = send_after
        if contact is not None:
            self.contact = contact
        if enabled is not None:
            self.enabled = enabled

    @property
    def parent(self):
        """Gets the parent of this NotificationRuleStep.  # noqa: E501


        :return: The parent of this NotificationRuleStep.  # noqa: E501
        :rtype: NotificationRuleStepParent
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this NotificationRuleStep.


        :param parent: The parent of this NotificationRuleStep.  # noqa: E501
        :type: NotificationRuleStepParent
        """

        self._parent = parent

    @property
    def id(self):
        """Gets the id of this NotificationRuleStep.  # noqa: E501


        :return: The id of this NotificationRuleStep.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NotificationRuleStep.


        :param id: The id of this NotificationRuleStep.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def send_after(self):
        """Gets the send_after of this NotificationRuleStep.  # noqa: E501


        :return: The send_after of this NotificationRuleStep.  # noqa: E501
        :rtype: Duration
        """
        return self._send_after

    @send_after.setter
    def send_after(self, send_after):
        """Sets the send_after of this NotificationRuleStep.


        :param send_after: The send_after of this NotificationRuleStep.  # noqa: E501
        :type: Duration
        """

        self._send_after = send_after

    @property
    def contact(self):
        """Gets the contact of this NotificationRuleStep.  # noqa: E501


        :return: The contact of this NotificationRuleStep.  # noqa: E501
        :rtype: ContactMeta
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this NotificationRuleStep.


        :param contact: The contact of this NotificationRuleStep.  # noqa: E501
        :type: ContactMeta
        """

        self._contact = contact

    @property
    def enabled(self):
        """Gets the enabled of this NotificationRuleStep.  # noqa: E501


        :return: The enabled of this NotificationRuleStep.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this NotificationRuleStep.


        :param enabled: The enabled of this NotificationRuleStep.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotificationRuleStep):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
