# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.filter import Filter  # noqa: F401,E501
from opsgenie_swagger.models.recipient import Recipient  # noqa: F401,E501
from opsgenie_swagger.models.time_restriction_interval import TimeRestrictionInterval  # noqa: F401,E501


class TeamRoutingRule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'is_default': 'bool',
        'order': 'int',
        'criteria': 'Filter',
        'timezone': 'str',
        'time_restriction': 'TimeRestrictionInterval',
        'notify': 'Recipient'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'is_default': 'isDefault',
        'order': 'order',
        'criteria': 'criteria',
        'timezone': 'timezone',
        'time_restriction': 'timeRestriction',
        'notify': 'notify'
    }

    def __init__(self, id=None, name=None, is_default=None, order=None, criteria=None, timezone=None, time_restriction=None, notify=None):  # noqa: E501
        """TeamRoutingRule - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._is_default = None
        self._order = None
        self._criteria = None
        self._timezone = None
        self._time_restriction = None
        self._notify = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if is_default is not None:
            self.is_default = is_default
        if order is not None:
            self.order = order
        if criteria is not None:
            self.criteria = criteria
        if timezone is not None:
            self.timezone = timezone
        if time_restriction is not None:
            self.time_restriction = time_restriction
        if notify is not None:
            self.notify = notify

    @property
    def id(self):
        """Gets the id of this TeamRoutingRule.  # noqa: E501


        :return: The id of this TeamRoutingRule.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TeamRoutingRule.


        :param id: The id of this TeamRoutingRule.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TeamRoutingRule.  # noqa: E501


        :return: The name of this TeamRoutingRule.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TeamRoutingRule.


        :param name: The name of this TeamRoutingRule.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_default(self):
        """Gets the is_default of this TeamRoutingRule.  # noqa: E501


        :return: The is_default of this TeamRoutingRule.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this TeamRoutingRule.


        :param is_default: The is_default of this TeamRoutingRule.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    @property
    def order(self):
        """Gets the order of this TeamRoutingRule.  # noqa: E501


        :return: The order of this TeamRoutingRule.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this TeamRoutingRule.


        :param order: The order of this TeamRoutingRule.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def criteria(self):
        """Gets the criteria of this TeamRoutingRule.  # noqa: E501


        :return: The criteria of this TeamRoutingRule.  # noqa: E501
        :rtype: Filter
        """
        return self._criteria

    @criteria.setter
    def criteria(self, criteria):
        """Sets the criteria of this TeamRoutingRule.


        :param criteria: The criteria of this TeamRoutingRule.  # noqa: E501
        :type: Filter
        """

        self._criteria = criteria

    @property
    def timezone(self):
        """Gets the timezone of this TeamRoutingRule.  # noqa: E501


        :return: The timezone of this TeamRoutingRule.  # noqa: E501
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """Sets the timezone of this TeamRoutingRule.


        :param timezone: The timezone of this TeamRoutingRule.  # noqa: E501
        :type: str
        """

        self._timezone = timezone

    @property
    def time_restriction(self):
        """Gets the time_restriction of this TeamRoutingRule.  # noqa: E501


        :return: The time_restriction of this TeamRoutingRule.  # noqa: E501
        :rtype: TimeRestrictionInterval
        """
        return self._time_restriction

    @time_restriction.setter
    def time_restriction(self, time_restriction):
        """Sets the time_restriction of this TeamRoutingRule.


        :param time_restriction: The time_restriction of this TeamRoutingRule.  # noqa: E501
        :type: TimeRestrictionInterval
        """

        self._time_restriction = time_restriction

    @property
    def notify(self):
        """Gets the notify of this TeamRoutingRule.  # noqa: E501


        :return: The notify of this TeamRoutingRule.  # noqa: E501
        :rtype: Recipient
        """
        return self._notify

    @notify.setter
    def notify(self, notify):
        """Sets the notify of this TeamRoutingRule.


        :param notify: The notify of this TeamRoutingRule.  # noqa: E501
        :type: Recipient
        """

        self._notify = notify

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TeamRoutingRule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
