# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TimelineRecipient(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'type': 'str',
        'forwarded_from': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'forwarded_from': 'forwardedFrom'
    }

    def __init__(self, id=None, name=None, type=None, forwarded_from=None):  # noqa: E501
        """TimelineRecipient - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._type = None
        self._forwarded_from = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if forwarded_from is not None:
            self.forwarded_from = forwarded_from

    @property
    def id(self):
        """Gets the id of this TimelineRecipient.  # noqa: E501


        :return: The id of this TimelineRecipient.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TimelineRecipient.


        :param id: The id of this TimelineRecipient.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TimelineRecipient.  # noqa: E501


        :return: The name of this TimelineRecipient.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TimelineRecipient.


        :param name: The name of this TimelineRecipient.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this TimelineRecipient.  # noqa: E501


        :return: The type of this TimelineRecipient.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TimelineRecipient.


        :param type: The type of this TimelineRecipient.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def forwarded_from(self):
        """Gets the forwarded_from of this TimelineRecipient.  # noqa: E501

        Only used by 'historical' period types  # noqa: E501

        :return: The forwarded_from of this TimelineRecipient.  # noqa: E501
        :rtype: str
        """
        return self._forwarded_from

    @forwarded_from.setter
    def forwarded_from(self, forwarded_from):
        """Sets the forwarded_from of this TimelineRecipient.

        Only used by 'historical' period types  # noqa: E501

        :param forwarded_from: The forwarded_from of this TimelineRecipient.  # noqa: E501
        :type: str
        """

        self._forwarded_from = forwarded_from

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimelineRecipient):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
