# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.time_restriction_interval import TimeRestrictionInterval  # noqa: F401,E501
from opsgenie_swagger.models.weekday_time_restriction import WeekdayTimeRestriction  # noqa: F401,E501


class WeekdayTimeRestrictionInterval(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'restrictions': 'list[WeekdayTimeRestriction]'
    }

    attribute_map = {
        'restrictions': 'restrictions'
    }

    def __init__(self, restrictions=None):  # noqa: E501
        """WeekdayTimeRestrictionInterval - a model defined in Swagger"""  # noqa: E501

        self._restrictions = None
        self.discriminator = None

        if restrictions is not None:
            self.restrictions = restrictions

    @property
    def restrictions(self):
        """Gets the restrictions of this WeekdayTimeRestrictionInterval.  # noqa: E501


        :return: The restrictions of this WeekdayTimeRestrictionInterval.  # noqa: E501
        :rtype: list[WeekdayTimeRestriction]
        """
        return self._restrictions

    @restrictions.setter
    def restrictions(self, restrictions):
        """Sets the restrictions of this WeekdayTimeRestrictionInterval.


        :param restrictions: The restrictions of this WeekdayTimeRestrictionInterval.  # noqa: E501
        :type: list[WeekdayTimeRestriction]
        """

        self._restrictions = restrictions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WeekdayTimeRestrictionInterval):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
