# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie OpenAPI Specification  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from opsgenie_swagger.models.action_mapping import ActionMapping  # noqa: F401,E501
from opsgenie_swagger.models.alert_filter import AlertFilter  # noqa: F401,E501
from opsgenie_swagger.models.bidirectional_callback_new import BidirectionalCallbackNew  # noqa: F401,E501


class ZendeskCallback(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'zendesk_api_token': 'str',
        'zendesk_email': 'str',
        'zendesk_subdomain': 'str'
    }

    attribute_map = {
        'zendesk_api_token': 'zendeskApiToken',
        'zendesk_email': 'zendeskEmail',
        'zendesk_subdomain': 'zendeskSubdomain'
    }

    def __init__(self, zendesk_api_token=None, zendesk_email=None, zendesk_subdomain=None):  # noqa: E501
        """ZendeskCallback - a model defined in Swagger"""  # noqa: E501

        self._zendesk_api_token = None
        self._zendesk_email = None
        self._zendesk_subdomain = None
        self.discriminator = None

        if zendesk_api_token is not None:
            self.zendesk_api_token = zendesk_api_token
        if zendesk_email is not None:
            self.zendesk_email = zendesk_email
        if zendesk_subdomain is not None:
            self.zendesk_subdomain = zendesk_subdomain

    @property
    def zendesk_api_token(self):
        """Gets the zendesk_api_token of this ZendeskCallback.  # noqa: E501


        :return: The zendesk_api_token of this ZendeskCallback.  # noqa: E501
        :rtype: str
        """
        return self._zendesk_api_token

    @zendesk_api_token.setter
    def zendesk_api_token(self, zendesk_api_token):
        """Sets the zendesk_api_token of this ZendeskCallback.


        :param zendesk_api_token: The zendesk_api_token of this ZendeskCallback.  # noqa: E501
        :type: str
        """

        self._zendesk_api_token = zendesk_api_token

    @property
    def zendesk_email(self):
        """Gets the zendesk_email of this ZendeskCallback.  # noqa: E501


        :return: The zendesk_email of this ZendeskCallback.  # noqa: E501
        :rtype: str
        """
        return self._zendesk_email

    @zendesk_email.setter
    def zendesk_email(self, zendesk_email):
        """Sets the zendesk_email of this ZendeskCallback.


        :param zendesk_email: The zendesk_email of this ZendeskCallback.  # noqa: E501
        :type: str
        """

        self._zendesk_email = zendesk_email

    @property
    def zendesk_subdomain(self):
        """Gets the zendesk_subdomain of this ZendeskCallback.  # noqa: E501


        :return: The zendesk_subdomain of this ZendeskCallback.  # noqa: E501
        :rtype: str
        """
        return self._zendesk_subdomain

    @zendesk_subdomain.setter
    def zendesk_subdomain(self, zendesk_subdomain):
        """Sets the zendesk_subdomain of this ZendeskCallback.


        :param zendesk_subdomain: The zendesk_subdomain of this ZendeskCallback.  # noqa: E501
        :type: str
        """

        self._zendesk_subdomain = zendesk_subdomain

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ZendeskCallback):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
